Deploy staging:
  # stage: staging
  type: deploy
  before_script:
    - apt-get update -qq
    - apt-get install -qq git
    # Setup SSH deploy keys
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh tamannaorange@67.227.213.5 "cd ~/api-np-service.tamanna.orangebd.com && git stash && git pull  && php artisan config:cache && php artisan cache:clear && rm -rf ~/api-np-service.tamanna.orangebd.com/public/storage && php artisan storage:link  && exit "
  environment:
    name: staging
    url: https://api-np-service.tamanna.orangebd.com/
  only:
    - master
